# Generated by Django 2.2.4 on 2019-08-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='CI_CO',
            field=models.CharField(choices=[('Check In', 'CHECK IN'), ('Check Out', 'CHECK OUT')], max_length=50, verbose_name='Check In/Check Out'),
        ),
    ]
